name: test
on:
  pull_request:    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd api && npm install && npm run test

name: build
on:
  pull_request:    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd api && npm install && npm run build     
